minVersion: '0.13.2'
github:
  owner: getsentry
  repo: sentry-javascript
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: github
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
    includeNames: /^sentry-.*$/
  - name: gcs
    includeNames: /.*\.js.*$/
    bucket: sentry-js-sdk
    paths:
      - path: /{{version}}/
        metadata:
          cacheControl: 'public, max-age=31536000'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-browser-.*\.tgz$/
    includeNames: /\.js$/
    checksums:
      - algorithm: sha384
        format: base64
    config:
      canonical: 'npm:csii-sentry-browser'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-node-.*\.tgz$/
    config:
      canonical: 'npm:csii-sentry-node'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-react-.*\.tgz$/
    config:
      canonical: 'npm:csii-sentry-react'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-vue-.*\.tgz$/
    config:
      canonical: 'npm:csii-sentry-vue'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-gatsby-.*\.tgz$/
    config:
      canonical: 'npm:csii-sentry-gatsby'
  - name: registry
    type: sdk
    onlyIfPresent: /^sentry-angular-.*\.tgz$/
    config:
      canonical: 'npm:csii-sentry-angular'
