git:
  depth: false # we need this to make proper releases

branches:
  only:
    - master
    - /^release\/.+$/
    - /^major\/.+$/

install: yarn --ignore-engines --ignore-scripts
os: linux

language: node_js
dist: bionic

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - name: 'csii-sentry-packages - build and test [node v6]'
      node_js: '6'
      script: scripts/test.sh
    - name: 'csii-sentry-packages - build and test [node v8]'
      node_js: '8'
      script: scripts/test.sh
    - name: 'csii-sentry-packages - build and test [node v10]'
      node_js: '10'
      script: scripts/test.sh
    - name: 'csii-sentry-packages - build and test [node v12]'
      node_js: '12'
      script: scripts/test.sh
    - name: '@sentry/packages - build and test [node v14]'
      node_js: '14'
      script: scripts/test.sh
